services:
    mh.skeleton.form.type.user_registration:
        class: MH\SkeletonBundle\Form\Type\RegistrationFormType
        arguments: [ "%fos_user.model.user.class%" ]
        tags:
            - { name: form.type, alias: mh_skeleton_form_type_user_registration }
