imports:
    - { resource: parameters.yml }
    - { resource: parameters_local.yml }
    - { resource: security.yml }
    - { resource: partial/framework.yml }
    - { resource: partial/assetic.yml }
    - { resource: partial/doctrine.yml }
    - { resource: partial/swiftmailer.yml }
    - { resource: partial/twig.yml }
    - { resource: partial/hwi_oauth.yml }
    - { resource: partial/fos_user.yml }
    - { resource: partial/mopa_bootstrap.yml }
