# Check this file for all available parameters. It's always better to change your settings in parameters_local.yml which
# allows you to override all of these parameters.
#

parameters:
    database_driver:   pdo_mysql
    database_host:     ~
    database_port:     ~
    database_name:     ~
    database_user:     ~
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
