services:
    mh.skeleton.form.type.user_registration:
        class: MH\UserBundle\Form\Type\RegistrationFormType
        arguments: [ "%fos_user.model.user.class%" ]
        tags:
            - { name: form.type, alias: mh_user_form_type_user_registration }
