hwi_oauth:
    firewall_name: main
    resource_owners:
        facebook:
            type:                facebook
            client_id:           <client_id>
            client_secret:       <client_secret>
            scope:               ""
        google:
            type:                google
            client_id:           <client_id>
            client_secret:       <client_secret>
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
        linked_in:
            type:                linkedin
            client_id:           <client_id>
            client_secret:       <client_secret>
        twitter:
            type:                twitter
            client_id:           <client_id>
            client_secret:       <client_secret>
        windows_live:
            type:                windows_live
            client_id:           <client_id>
            client_secret:       <client_secret>
            scope:               ""
    fosub:
        # try 30 times to check if a username is available (foo, foo1, foo2 etc)
        username_iterations: 30

        # mapping between resource owners (see below) and properties
        properties:
            github: githubId
            google: googleId
            facebook: facebookId
            linked_in: linkedInId
            windows_live: windowsLiveId
