hwi_oauth:
    firewall_name: main
    resource_owners:
        facebook:
            type:                facebook
            client_id:           %facebook_id%
            client_secret:       %facebook_secret%
            scope:               ""
        google:
            type:                google
            client_id:           %google_id%
            client_secret:       %google_secret%
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
        linked_in:
            type:                linkedin
            client_id:           %linked_in_id%
            client_secret:       %linked_in_secret%
        twitter:
            type:                twitter
            client_id:           %twitter_id%
            client_secret:       %twitter_secret%
        windows_live:
            type:                windows_live
            client_id:           %windows_live_id%
            client_secret:       %windows_live_secret%
            scope:               ""
    fosub:
        # try 30 times to check if a username is available (foo, foo1, foo2 etc)
        username_iterations: 30

        # mapping between resource owners (see below) and properties
        properties:
            github: githubId
            google: googleId
            facebook: facebookId
            linked_in: linkedInId
            windows_live: windowsLiveId
