facebook_login:
    pattern: /check-facebook

google_login:
    pattern: /check-google

linked_in_login:
    pattern: /check-linked-in

twitter_login:
    pattern: /check-twitter

windows_live_login:
    pattern: /check-windows-live
